### ISSUE TITLE
Collect extra data like validation rules when creating a new publication type field definition

### ISSUE THREAD

**Issue by emmadesilva** [hydephp/publications#5]
Here we could collect other data like the "rules" array for the field. [`MakePublicationTypeCommand.php#L104`](https://github.com/hydephp/develop/blob/25ab457a84d5ab5cac906eb75a3890d9880eec1d/packages/publications/src/Commands/MakePublicationTypeCommand.php#L104)

[![github com_hydephp_develop_pull_685](https://user-images.githubusercontent.com/95144705/217784283-ef8b4442-206a-4acd-a3a3-f5d602ad1a3b.png)
](https://github.com/hydephp/develop/blob/25ab457a84d5ab5cac906eb75a3890d9880eec1d/packages/publications/src/Commands/MakePublicationTypeCommand.php#L104)

**Comment by emmadesilva** [comment]
@rgasch What do you think about this? Is custom validation rules common enough to bother the user by asking for them on each field generation?

**Comment by robertgdev** [comment]
IMHO, this would be almost never used ... I could be wrong however

**Comment by emmadesilva** [comment]
> IMHO, this would be almost never used ... I could be wrong however

Agreed. Will remove the todo marker next time I'm on the branch. Thanks for the input!

**Comment by emmadesilva** [comment]
Closing as wontfix in https://github.com/hydephp/develop/commit/2dc0d9aea33ab2b1c8b83e45ce6f05aafa0a0b19
